source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'haml'
gem 'json2-rails'
gem 'spine-rails'
gem 'eco'
gem 'hamlbars'
gem 'handlebars_assets'

